Hc vs Pre
```{r setup, include=FALSE}
install.packages("effsize")
library(effsize)
install.packages("rcompanion")
library(rcompanion)



data = read.csv(file = '/Users/paulamun/Desktop/GoNoGo_Committee_meeting/BITS_Harmonized_Data_Incorrect_SIR_RemoveHC_Other_Study.csv')

data=data[,-c(1,8,9,10,11,12)]

HC_data <- data[data$HD1 == 0, ]
PreHD_data <- data[data$HD1 == 1 & data$PreBITS0_PostBITS1 == 0, ]
PostHD_data <- data[data$HD1 == 1 & data$PreBITS0_PostBITS1 == 1, ]

#Rigth Insula
# Calculate Cohen's d for unpaired comparison
effect_size <- cohen.d(HC_data$Right_Insula, PreHD_data$Right_Insula, paired = FALSE)
print(effect_size)


# For an independent (two-sample) t-test
group1 <- c(10, 12, 9, 11, 13)
group2 <- c(14, 15, 13, 16, 14)
t.test(group1, group2, var.equal = TRUE)  # Set var.equal = FALSE if variances differ


mann_whitney <- wilcox.test(PreHD_data$Right_Insula, HC_data$Right_Insula, alternative = "greater", paired = FALSE)
print(mann_whitney)
# Extract U statistic from the test
U <- mann_whitney$statistic

cliff_delta <- cliff.delta(HC_data$Right_Insula, PreHD_data$Right_Insula)
print(cliff_delta)

# Calculate sample sizes
n1 <- length(HC_data$Right_Insula)
n2 <- length(PreHD_data$Right_Insula)

# Calculate rank-biserial correlation manually
rank_biserial_manual <- 1 - (2 * U) / (n1 * n2)
print(rank_biserial_manual)


#Calculate SE

# Define the sample sizes of each group
n1 <- length(HC_data$Right_Insula)  # Sample size of group 1
n2 <- length(PreHD_data$Right_Insula)  # Sample size of group 2

# Calculate the standard error of the U statistic
SE_U <- sqrt((n1 * n2 * (n1 + n2 + 1)) / 12)
print(SE_U)

# SE HC
data <- c(HC_data$Right_Insula)
SD <- sd(data)
n <- length(data)
SE <- SD / sqrt(n)
print(SE)

# SE Pre-BIT+
data <- c(PreHD_data$Right_Insula)
SD <- sd(data)
n <- length(data)
SE <- SD / sqrt(n)
print(SE)

# Calculate the standard deviation
SD <- sd(HC_data$Right_Insula)
print(SD)

# Calculate the standard deviation
SD <- sd(PreHD_data$Right_Insula)
print(SD)
____________________________________________________________________________________________________________________
#Left Insula

# Calculate Cohen's d for unpaired comparison
effect_size <- cohen.d(HC_data$Left_Insula, PreHD_data$Left_Insula, paired = FALSE)
print(effect_size)

)
# Remove rows with NA values in the combined dataset
Left_Insula_combined <- Left_Insula_combined[!is.na(Left_Insula_combined$value), ]


mann_whitney <- wilcox.test(PreHD_data$Left_Insula, HC_data$Left_Insula, alternative = "greater", paired = FALSE, 
                      exact = TRUE)
print(mann_whitney_test)
# Extract U statistic from the test
U <- mann_whitney$statistic

cliff_delta <- cliff.delta(HC_data$Left_Insula, PreHD_data$Left_Insula)
print(cliff_delta)

# Calculate sample sizes
n1 <- length(HC_data$Left_Insula)
n2 <- length(PreHD_data$Left_Insula)

# Calculate rank-biserial correlation manually
rank_biserial_manual <- 1 - (2 * U) / (n1 * n2)
print(rank_biserial_manual)


#Calculate SE

# Define the sample sizes of each group
n1 <- length(HC_data$Left_Insula)  # Sample size of group 1
n2 <- length(PreHD_data$Left_Insula)  # Sample size of group 2

# Calculate the standard error of the U statistic
SE_U <- sqrt((n1 * n2 * (n1 + n2 + 1)) / 12)
print(SE_U)

# Calculate rank-biserial correlation manually
rank_biserial_manual <- 1 - (2 * U) / (n1 * n2)
print(rank_biserial_manual)


# Calculate the standard deviation
SD <- sd(HC_data$Left_Insula)
print(SD)

# Calculate the standard deviation
SD <- sd(PreHD_data$Left_Insula)
print(SD)

# SE HC
data <- c(HC_data$Left_Insula)
SD <- sd(data)
n <- length(data)
SE <- SD / sqrt(n)
print(SE)

# SE Pre-BIT+
data <- c(PreHD_data$Left_Insula)
SD <- sd(data)
n <- length(data)
SE <- SD / sqrt(n)
print(SE)

____________________________________________________________________________________________________________________
#ACC

# Calculate Cohen's d for unpaired comparison
effect_size <- cohen.d(HC_data$ACC, PreHD_data$ACC, paired = FALSE)
print(effect_size)

mann_whitney <- wilcox.test(PreHD_data$ACC, HC_data$ACC, alternative = "greater", paired = FALSE)
print(mann_whitney)
# Extract U statistic from the test
U <- mann_whitney$statistic

cliff_delta <- cliff.delta(HC_data$ACC, PreHD_data$ACC)
print(cliff_delta)

# Calculate sample sizes
n1 <- length(HC_data$ACC)
n2 <- length(PreHD_data$ACC)

# Calculate rank-biserial correlation manually
rank_biserial_manual <- 1 - (2 * U) / (n1 * n2)
print(rank_biserial_manual)


#Calculate SE

# Define the sample sizes of each group
n1 <- length(HC_data$ACC)  # Sample size of group 1
n2 <- length(PreHD_data$ACC)  # Sample size of group 2

# Calculate the standard error of the U statistic
SE_U <- sqrt((n1 * n2 * (n1 + n2 + 1)) / 12)
print(SE_U)

# SE HC
data <- c(HC_data$ACC)
SD <- sd(data)
n <- length(data)
SE <- SD / sqrt(n)
print(SE)

# SE Pre-BIT+
data <- c(PreHD_data$ACC)
SD <- sd(data)
n <- length(data)
SE <- SD / sqrt(n)
print(SE)

# Calculate the standard deviation
SD <- sd(HC_data$ACC)
print(SD)

# Calculate the standard deviation
SD <- sd(PreHD_data$ACC)
print(SD)


```


HC vs Post
```{r setup, include=FALSE}

data = read.csv(file = '/Users/paulamun/Desktop/GoNoGo_Committee_meeting/BITS_Harmonized_Data_Incorrect_SIR_RemoveHC_Other_Study.csv')

data=data[,-c(1,8,9,10,11,12)]

HC_data <- data[data$HD1 == 0, ]
PreHD_data <- data[data$HD1 == 1 & data$PreBITS0_PostBITS1 == 0, ]
PostHD_data <- data[data$HD1 == 1 & data$PreBITS0_PostBITS1 == 1, ]

#Rigth Insula
# Calculate Cohen's d for unpaired comparison
effect_size <- cohen.d(HC_data$Right_Insula, PostHD_data$Right_Insula, paired = FALSE)
print(effect_size)

mann_whitney <- wilcox.test(PostHD_data$Right_Insula, HC_data$Right_Insula, alternative = "greater", paired = FALSE)
print(mann_whitney)
# Extract U statistic from the test
U <- mann_whitney$statistic

cliff_delta <- cliff.delta(HC_data$Right_Insula, PostHD_data$Right_Insula)
print(cliff_delta)

# Calculate sample sizes
n1 <- length(HC_data$Right_Insula)
n2 <- length(PostHD_data$Right_Insula)

# Calculate rank-biserial correlation manually
rank_biserial_manual <- 1 - (2 * U) / (n1 * n2)
print(rank_biserial_manual)


#Calculate SE

# Define the sample sizes of each group
n1 <- length(HC_data$Right_Insula)  # Sample size of group 1
n2 <- length(PostHD_data$Right_Insula)  # Sample size of group 2

# Calculate the standard error of the U statistic
SE_U <- sqrt((n1 * n2 * (n1 + n2 + 1)) / 12)
print(SE_U)

# SE HC
data <- c(HC_data$Right_Insula)
SD <- sd(data)
n <- length(data)
SE <- SD / sqrt(n)
print(SE)

# SE Pre-BIT+
data <- c(PostHD_data$Right_Insula)
SD <- sd(data)
n <- length(data)
SE <- SD / sqrt(n)
print(SE)

# Calculate the standard deviation
SD <- sd(HC_data$Right_Insula)
print(SD)

# Calculate the standard deviation
SD <- sd(PostHD_data$Right_Insula)
print(SD)
____________________________________________________________________________________________________________________
#Left Insula

# Calculate Cohen's d for unpaired comparison
effect_size <- cohen.d(HC_data$Left_Insula, PostHD_data$Left_Insula, paired = FALSE)
print(effect_size)

)
# Remove rows with NA values in the combined dataset
Left_Insula_combined <- Left_Insula_combined[!is.na(Left_Insula_combined$value), ]


mann_whitney <- wilcox.test(PostHD_data$Left_Insula, HC_data$Left_Insula, alternative = "greater", paired = FALSE, 
                      exact = TRUE)
print(mann_whitney)
# Extract U statistic from the test
U <- mann_whitney$statistic

cliff_delta <- cliff.delta(HC_data$Left_Insula, PostHD_data$Left_Insula)
print(cliff_delta)

# Calculate sample sizes
n1 <- length(HC_data$Left_Insula)
n2 <- length(PostHD_data$Left_Insula)

# Calculate rank-biserial correlation manually
rank_biserial_manual <- 1 - (2 * U) / (n1 * n2)
print(rank_biserial_manual)


#Calculate SE

# Define the sample sizes of each group
n1 <- length(HC_data$Left_Insula)  # Sample size of group 1
n2 <- length(PostHD_data$Left_Insula)  # Sample size of group 2

# Calculate the standard error of the U statistic
SE_U <- sqrt((n1 * n2 * (n1 + n2 + 1)) / 12)
print(SE_U)

# Calculate rank-biserial correlation manually
rank_biserial_manual <- 1 - (2 * U) / (n1 * n2)
print(rank_biserial_manual)


# Calculate the standard deviation
SD <- sd(HC_data$Left_Insula)
print(SD)

# Calculate the standard deviation
SD <- sd(PostHD_data$Left_Insula)
print(SD)

# SE HC
data <- c(HC_data$Left_Insula)
SD <- sd(data)
n <- length(data)
SE <- SD / sqrt(n)
print(SE)

# SE Pre-BIT+
data <- c(PostHD_data$Left_Insula)
SD <- sd(data)
n <- length(data)
SE <- SD / sqrt(n)
print(SE)
```
____________________________________________________________________________________________________________________
```{r}
#ACC

# Calculate Cohen's d for unpaired comparison
effect_size <- cohen.d(HC_data$ACC, PostHD_dataACC, paired = FALSE)
print(effect_size)

mann_whitney <- wilcox.test(PostHD_data$ACC, HC_data$ACC, alternative = "greater", paired = FALSE)
print(mann_whitney)
# Extract U statistic from the test
U <- mann_whitney$statistic

cliff_delta <- cliff.delta(HC_data$ACC, PostHD_data$ACC)
print(cliff_delta)

# Calculate sample sizes
n1 <- length(HC_data$ACC)
n2 <- length(PostHD_data$ACC)

# Calculate rank-biserial correlation manually
rank_biserial_manual <- 1 - (2 * U) / (n1 * n2)
print(rank_biserial_manual)


#Calculate SE

# Define the sample sizes of each group
n1 <- length(HC_data$ACC)  # Sample size of group 1
n2 <- length(PostHD_data$ACC)  # Sample size of group 2

# Calculate the standard error of the U statistic
SE_U <- sqrt((n1 * n2 * (n1 + n2 + 1)) / 12)
print(SE_U)

# SE HC
data <- c(HC_data$ACC)
SD <- sd(data)
n <- length(data)
SE <- SD / sqrt(n)
print(SE)

# SE Pre-BIT+
data <- c(PostHD_data$ACC)
SD <- sd(data)
n <- length(data)
SE <- SD / sqrt(n)
print(SE)

# Calculate the standard deviation
SD <- sd(HC_data$ACC)
print(SD)

# Calculate the standard deviation
SD <- sd(PostHD_data$ACC)
print(SD)

```


HD: Pre vs Post
```{r setup, include=FALSE}

data = read.csv(file = '/Users/paulamun/Desktop/GoNoGo_Committee_meeting/BITS_Harmonized_Data_Incorrect_SIR_RemoveHC_Other_Study.csv')

data=data[,-c(1,8,9,10,11,12)]

HC_data <- data[data$HD1 == 0, ]
PreHD_data <- data[data$HD1 == 1 & data$PreBITS0_PostBITS1 == 0, ]
PostHD_data <- data[data$HD1 == 1 & data$PreBITS0_PostBITS1 == 1, ]

#Rigth Insula
# Calculate Cohen's d for unpaired comparison
effect_size <- cohen.d(PreHD_data$Right_Insula, PostHD_data$Right_Insula, paired = FALSE)
print(effect_size)

# Example paired data
before <- c(PreHD_data$Right_Insula)
after <- c(PostHD_data$Right_Insula)

# Example paired data
before <- c(PreHD_data$ACC)
after <- c(PostHD_data$ACC)

# remove subjects without observations at both timepoints
subjectsPost=PostHD_data$subject
PreWithPost_HD_data = PreHD_data[PreHD_data$subject %in% subjectsPost, ]

# Perform a one-tailed Wilcoxon signed-rank test (alternative: after > before)
wilcox_paired_result <- wilcox.test(PreWithPost_HD_data$Right_Insula, PostHD_data$Right_Insula, 
                                    alternative = "greater", 
                                    paired = TRUE)
# Print the result
print(paste0('the final p-value for pre vs. post BITS ACC activity is:', wilcox_paired_result$p.value))

cliff_delta <- cliff.delta(PreHD_data$Right_Insula, PostHD_data$Right_Insula)
print(cliff_delta)

# Calculate sample sizes
n1 <- length(PreHD_data$Right_Insula)
n2 <- length(PostHD_data$Right_Insula)

# Calculate rank-biserial correlation manually
rank_biserial_manual <- 1 - (2 * U) / (n1 * n2)
print(rank_biserial_manual)


#Calculate SE

# Define the sample sizes of each group
n1 <- length(PreHD_data$Right_Insula)  # Sample size of group 1
n2 <- length(PostHD_data$Right_Insula)  # Sample size of group 2

# Calculate the standard error of the U statistic
SE_U <- sqrt((n1 * n2 * (n1 + n2 + 1)) / 12)
print(SE_U)

# SE Pre-BIT+
data <- c(PreHD_data$Right_Insula)
SD <- sd(data)
n <- length(data)
SE <- SD / sqrt(n)
print(SE)

# SE Post-BIT+
data <- c(PostHD_data$Right_Insula)
SD <- sd(data)
n <- length(data)
SE <- SD / sqrt(n)
print(SE)

# Calculate the standard deviation
SD <- sd(PreHD_data$Right_Insula)
print(SD)

# Calculate the standard deviation
SD <- sd(PostHD_data$Right_Insula)
print(SD)
____________________________________________________________________________________________________________________
#Left Insula

# Calculate Cohen's d for unpaired comparison
effect_size <- cohen.d(PreHD_data$Left_Insula, PostHD_data$Left_Insula, paired = FALSE)
print(effect_size)

# Remove rows with NA values in the combined dataset
Left_Insula_combined <- Left_Insula_combined[!is.na(Left_Insula_combined$value), ]


# Example paired data
before <- c(PreHD_data$Left_Insula)
after <- c(PostHD_data$Left_Insula)

# Example paired data
before <- c(PreHD_data$Left_Insula)
after <- c(PostHD_data$Left_Insula)

# remove subjects without observations at both timepoints
subjectsPost=PostHD_data$subject
PreWithPost_HD_data = PreHD_data[PreHD_data$subject %in% subjectsPost, ]

# Perform a one-tailed Wilcoxon signed-rank test (alternative: after > before)
wilcox_paired_result <- wilcox.test(PreWithPost_HD_data$Left_Insula, PostHD_data$Left_Insula, 
                                    alternative = "greater", 
                                    paired = TRUE)
# Print the result
print(paste0('the final p-value for pre vs. post BITS ACC activity is:', wilcox_paired_result$p.value))

# Calculate sample sizes
n1 <- length(PreHD_data$Left_Insula)
n2 <- length(PostHD_data$Left_Insula)

# Calculate rank-biserial correlation manually
rank_biserial_manual <- 1 - (2 * U) / (n1 * n2)
print(rank_biserial_manual)


#Calculate SE

# Define the sample sizes of each group
n1 <- length(PreHD_data$Left_Insula)  # Sample size of group 1
n2 <- length(PostHD_data$Left_Insula)  # Sample size of group 2

# Calculate the standard error of the U statistic
SE_U <- sqrt((n1 * n2 * (n1 + n2 + 1)) / 12)
print(SE_U)

# Calculate rank-biserial correlation manually
rank_biserial_manual <- 1 - (2 * U) / (n1 * n2)
print(rank_biserial_manual)


# Calculate the standard deviation
SD <- sd(PreHD_data$Left_Insula)
print(SD)

# Calculate the standard deviation
SD <- sd(PostHD_data$Left_Insula)
print(SD)

# SE Pre-BIT+
data <- c(PreHD_data$Left_Insula)
SD <- sd(data)
n <- length(data)
SE <- SD / sqrt(n)
print(SE)

# SE Post-BIT+
data <- c(PostHD_data$Left_Insula)
SD <- sd(data)
n <- length(data)
SE <- SD / sqrt(n)
print(SE)

____________________________________________________________________________________________________________________
#ACC

# Calculate Cohen's d for unpaired comparison
effect_size <- cohen.d(PreHD_data$ACC, PostHD_dataACC, paired = FALSE)
print(effect_size)

# Example paired data
before <- c(PreHD_data$ACC)
after <- c(PostHD_data$ACC)

# remove subjects without observations at both timepoints
subjectsPost=PostHD_data$subject
PreWithPost_HD_data = PreHD_data[PreHD_data$subject %in% subjectsPost, ]

# Perform a one-tailed Wilcoxon signed-rank test (alternative: after > before)
wilcox_paired_result <- wilcox.test(PreWithPost_HD_data$ACC, PostHD_data$ACC, 
                                    alternative = "greater", 
                                    paired = TRUE)
# Print the result
print(paste0('the final p-value for pre vs. post BITS ACC activity is:', wilcox_paired_result$p.value))

cliff_delta <- cliff.delta(PreHD_data$ACC, PostHD_data$ACC)
print(cliff_delta)

# Calculate sample sizes
n1 <- length(PreHD_data$ACC)
n2 <- length(PostHD_data$ACC)

# Calculate rank-biserial correlation manually
rank_biserial_manual <- 1 - (2 * U) / (n1 * n2)
print(rank_biserial_manual)

#Calculate SE

# Define the sample sizes of each group
n1 <- length(PreHD_data$ACC)  # Sample size of group 1
n2 <- length(PostHD_data$ACC)  # Sample size of group 2

# Calculate the standard error of the U statistic
SE_U <- sqrt((n1 * n2 * (n1 + n2 + 1)) / 12)
print(SE_U)

# SE Pre-BIT+
data <- c(PreHD_data$ACC)
SD <- sd(data)
n <- length(data)
SE <- SD / sqrt(n)
print(SE)

# SE Post-BIT+
data <- c(PostHD_data$ACC)
SD <- sd(data)
n <- length(data)
SE <- SD / sqrt(n)
print(SE)

# Calculate the standard deviation Pre-BIT+
SD <- sd(PreHD_data$ACC)
print(SD)

# Calculate the standard deviation Post-BIT+
SD <- sd(PostHD_data$ACC)
print(SD)


```
```{r cars}
summary(cars)
```

